[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
board_build.flash_size = 16MB
board_build.psram_type = opi
board_upload.flash_size = 16MB
monitor_speed = 115200
lib_deps =
  https://github.com/shorepine/AMY
  adafruit/Adafruit SH110X@^2.1.8
  adafruit/Adafruit GFX Library@^1.11.9
  greiman/SdFat@^2.2.3
  adafruit/Adafruit NeoPixel@^1.12.0
build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DCORE_DEBUG_LEVEL=0
